### ISSUE TITLE
Eventual consistency with writing metric descriptors

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-monitoring#190]
It's hard to say if this is an issue with the API or with the client library.  In the sample tests, we're experiencing eventual consistency with writing metric descriptors.  See the following in the tests:

```js
it('should create a metric descriptors', async () => {
    const output = await exec(`${cmd} create`);
    assert.match(output, /Created custom Metric/);
    assert.match(output, new RegExp(`Type: ${customMetricId}`));
  });

  it('should list metric descriptors, including the new custom one', async () => {
    
    await retry(
      async () => {
        const output = await exec(`${cmd} list`);
        assert.match(output, new RegExp(customMetricId));
        assert.match(output, new RegExp(computeMetricId));
      },
      {
        retries: 10,
        onFailedAttempt: () => console.warn('Read failed, retrying...')
      }
    );
  });
```

With exponential backoff, it's not uncommon for this to retry 6-7 times before finally being able to do the read.

**Comment by bcoe** [comment]
Talked to folks working on the upstream API, and can confirm that this is expected behavior; their feeling is it stinks for tests, but it shouldn't bite customers too often in a day to day situation.

The advice was not to document the method, as behavior is potentially subject to change in the future.
